# Generated by Django 5.0.6 on 2024-07-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('text', models.CharField(max_length=4000, verbose_name='Text')),
                ('translation', models.CharField(max_length=4000, verbose_name='Translation')),
            ],
        ),
    ]
